### ISSUE TITLE
QRCode na última versão do ChatWoot

### ISSUE THREAD

**Issue by tizum** [w3nder/chatwoot-codechat#11]
Ao utilizar para ultima versão do ChatWoot 2.17.1 ao enviar /iniciar o QRCode não chega, demora cerca de 1 minuto e envia que o limite foi atingido, ao enviar a mensagem /iniciar algumas vezes em seguida, ele envia o QRCode, porém já chega expirado.

**Comment by caoramos** [comment]
Outro issue relacionado ao update para a versão 2.17.1 é que não é possível receber mensagens vindas do usuario que não seja texto. O atendente consegue enviar texto, imagem, video, arquivo mas só está recebendo isso. Mesmo com o update previsto no Chatwoot para resolver a questão do audio em WAV para OGA. Rodei testes nas versões 2.17.0, 2.17.1 e develop (com o patch para corrigir o audio de WAV para OGA). Não funcionou o recebimento de mensagens bem como a geração do QRCODE.

Vou anexar o log do conector.
[_cccpxpcpzi_cccpxpcpzi.1.l676kvqp9tqr7qlzkt5i6r826_logs.txt](https://github.com/w3nder/chatwoot-codechat/files/11558076/_cccpxpcpzi_cccpxpcpzi.1.l676kvqp9tqr7qlzkt5i6r826_logs.txt)

**Comment by caoramos** [comment]
Anexo aqui 
![Screenshot - 2023-05-24T153944 234](https://github.com/w3nder/chatwoot-codechat/assets/11988813/54252aef-44f1-44c0-b07c-6d63c570ba2d)
![Screenshot - 2023-05-24T154017 235](https://github.com/w3nder/chatwoot-codechat/assets/11988813/6f11df60-b8d2-47fd-896f-d3bde924a3da)
![Screenshot - 2023-05-24T154033 211](https://github.com/w3nder/chatwoot-codechat/assets/11988813/7b0ef9f5-9602-45ac-963c-c573e35ae55b)
os prints para verificar que as mensagens são enviadas pelo usuario mas nao recebidas no chatwoot.

Envio também a URL de um video que gravei sobre a questão da geração do QRCode.
https://watch.screencastify.com/v/aWeu6gh5fOcSwvLBIH9J

**Comment by w3nder** [comment]
Olá, obrigado pelo o reporte bem detalhado, irei trabalhar na correção.
